services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: japan-history-map-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    tty: true
    environment:
      - NODE_ENV=development